---
- name: 'Create data folder'
  file:
    dest: '{{ nim_waku_node_db_path }}'
    state: 'directory'
    owner: dockremap
    group: docker
    mode: 0775

- name: Create script for calling RPC endpoint
  template:
    src: 'rpc.sh.j2'
    dest: '{{ nim_waku_cont_vol }}/rpc.sh'
    owner: dockremap
    group: docker
    mode: 0755

- name: 'Create compose file: {{ nim_waku_cont_name }}'
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ nim_waku_cont_vol }}/docker-compose.yml'
    owner: dockremap
    group: docker
    mode: 0644

- name: 'Create container: {{ nim_waku_cont_name }}'
  docker_compose:
    project_src: '{{ nim_waku_cont_vol }}'
    pull: true
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ compose_recreate }}'
    # Avoid deprecation warning
    tls_hostname: 'localhost'

# FIXME: Drop once websockets issue is resolved:
# https://github.com/status-im/nwaku/issues/1186
- name: Temporary periodic container restart
  include_role: name=systemd-timer
  vars:
    systemd_timer_name: 'restart-{{ nim_waku_cont_name }}'
    systemd_timer_description: 'Restart of {{ nim_waku_cont_name }} container'
    systemd_timer_documentation: 'https://github.com/status-im/nwaku/issues/1186'
    systemd_timer_start_on_creation: false
    systemd_timer_user: 'root'
    systemd_timer_consul_warning: true
    systemd_timer_frequency: '00/06:00' # every 6 hours
    systemd_timer_random_delay_sec: 11600 # 2 hours
    systemd_timer_script_path: '/usr/bin/docker'
    systemd_timer_script_args: 'restart {{ nim_waku_cont_name }}'
